name: .NET Build and Docker

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Motivo da execução'
        required: false
        default: 'Rodar Pipeline'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Postech.Fase3.Contatos.Delete.Service/Dockerfile
        push: false
        tags: postech-contatos-delete:latest
        load: true